// Generated by CoffeeScript 1.6.3
(function() {
  this.App = (function() {
    function App(_opts) {
      this.options = _opts || {};
      this.init();
    }

    App.prototype.init = function() {
      var _this = this;
      this._initVfx();
      this.scene = this._createScene();
      return requestAnimationFrame(function() {
        _this.update();
        return _this.draw();
      });
    };

    App.prototype._initVfx = function() {
      this.camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 1, 10000);
      this.camera.position.z = 500;
      this.renderer = new THREE.WebGLRenderer({
        preserveDrawingBuffer: true
      });
      this.renderer.setSize(window.innerWidth, window.innerHeight);
      return document.body.appendChild(this.renderer.domElement);
    };

    App.prototype._createScene = function() {
      var cube, geometry, material, scene;
      scene = new THREE.Scene();
      geometry = new THREE.CubeGeometry(1, 1, 1);
      material = new THREE.MeshBasicMaterial({
        color: 0x00ff00
      });
      cube = new THREE.Mesh(geometry, material);
      scene.add(cube);
      this.camera.position.z = 5;
      return scene;
    };

    App.prototype.update = function() {
      if (this.paused) {

      }
    };

    App.prototype.draw = function() {
      return this.renderer.render(this.scene, this.camera);
    };

    App.prototype.togglePause = function() {
      this.paused = this.paused !== true;
      if (this.paused) {
        return console.log('Paused');
      } else {
        return console.log('Continue');
      }
    };

    return App;

  })();

}).call(this);
