// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.App = (function(_super) {
    __extends(App, _super);

    function App(_opts) {
      this.options = _opts || {};
      this.init();
    }

    App.prototype.init = function() {
      this._initVfx();
      this._createScene();
      return this.update();
    };

    App.prototype._initVfx = function() {
      this.camera = new THREE.PerspectiveCamera(45, window.innerWidth / window.innerHeight, 1, 1000);
      this.renderer = new THREE.WebGLRenderer();
      this._resize();
      $(window).resize(this._resize);
      return document.body.appendChild(this.renderer.domElement);
    };

    App.prototype._resize = function(event) {
      if (this.camera) {
        this.camera.aspect = window.innerWidth / window.innerHeight;
        this.camera.updateProjectionMatrix();
      }
      if (this.renderer) {
        return this.renderer.setSize(window.innerWidth, window.innerHeight);
      }
    };

    App.prototype._createScene = function() {
      this.scene = new THREE.Scene();
      this.dripper = new Dripper({
        scene: this.scene,
        camera: this.camera
      });
      this.on('update', (function() {
        return this.dripper.update();
      }), this);
      this.camera_operator = new CameraOperator({
        camera: this.camera,
        scene: this.scene,
        speed: 3
      });
      this.on('update', (function() {
        return this.camera_operator.update();
      }), this);
      this.post_processor = new PostProcessor({
        renderer: this.renderer,
        camera: this.camera,
        scene: this.scene
      });
      this.on('update', (function() {
        return this.post_processor.update();
      }), this);
      return this.scene;
    };

    App.prototype.update = function() {
      var _this = this;
      requestAnimationFrame(function() {
        _this.update();
        return _this.draw();
      });
      if (this.paused) {
        return;
      }
      return this.trigger('update');
    };

    App.prototype.draw = function() {
      if (this.post_processor) {
        this.post_processor.composer.render();
        return;
      }
      return this.renderer.render(this.scene, this.camera);
    };

    App.prototype.togglePause = function() {
      this.paused = this.paused !== true;
      if (this.paused) {
        return console.log('Paused');
      } else {
        return console.log('Continue');
      }
    };

    return App;

  })(Backbone.Model);

}).call(this);
