// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.CameraOperator = (function(_super) {
    __extends(CameraOperator, _super);

    function CameraOperator(_opts) {
      this.options = _opts || {};
      this.init();
    }

    CameraOperator.prototype.init = function() {
      this.destroy();
      this.scene = this.options.scene;
      this.camera = this.options.camera;
      return this.camera.position.z = 5;
    };

    CameraOperator.prototype.destroy = function() {
      this.trigger('destroy');
      return this.scene = this.camera = void 0;
    };

    CameraOperator.prototype.update = function() {
      return this.camera.position.z += this.speed();
    };

    CameraOperator.prototype.speed = function() {
      return this.options.speed || 0.01;
    };

    return CameraOperator;

  })(Backbone.Model);

}).call(this);
