// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.CameraOperator = (function(_super) {
    __extends(CameraOperator, _super);

    function CameraOperator(_opts) {
      this.options = _opts || {};
      this.init();
    }

    CameraOperator.prototype.init = function() {
      this.destroy();
      this.scene = this.options.scene;
      this.camera = this.options.camera;
      this.camera.position.z = 0;
      this.light = new THREE.PointLight(0xFF0000);
      this.light.position.x = 10;
      this.light.position.y = 50;
      this.light.position.copy(this.camera.position);
      this.light.position.x += 3;
      this.light.position.y += 3;
      return this.scene.add(this.light);
    };

    CameraOperator.prototype.destroy = function() {
      this.trigger('destroy');
      if (this.light) {
        this.scene.remove(this.light);
        this.light = void 0;
      }
      return this.scene = this.camera = void 0;
    };

    CameraOperator.prototype.update = function() {
      this.camera.position.z += this.speed();
      this.camera.rotation.z += this.options.rotation_speed || 0.001;
      return this.light.position.z = this.camera.position.z;
    };

    CameraOperator.prototype.speed = function() {
      return this.options.speed || 0.01;
    };

    return CameraOperator;

  })(Backbone.Model);

}).call(this);
