// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.Dripper = (function(_super) {
    __extends(Dripper, _super);

    function Dripper(_opts) {
      this.options = _opts || {};
      this.init();
    }

    Dripper.prototype.init = function() {
      this.destroy();
      this.scene = this.options.scene;
      this.camera = this.options.camera;
      this.geometry = new THREE.CubeGeometry(1, 1, 1);
      this.material = new THREE.MeshBasicMaterial({
        color: 0x00ff00
      });
      return this.drips = [];
    };

    Dripper.prototype.destroy = function() {
      this.trigger('destroy');
      if (this.cube) {
        this.scene.remove(this.cube);
        this.cube = void 0;
      }
      return this.scene = this.camera = void 0;
    };

    Dripper.prototype.generateDrip = function() {
      var mesh;
      mesh = new THREE.Mesh(this.geometry, this.material);
      mesh.position.z = this.camera.position.z;
      mesh.position.x = -5 + Math.random() * 10;
      mesh.position.y = -5 + Math.random() * 10;
      return mesh;
    };

    Dripper.prototype.update = function() {
      var curDrip, drip;
      curDrip = new Date().getTime();
      if (this.lastDrip && (curDrip - this.lastDrip) < 500) {
        return;
      }
      this.lastDrip = curDrip;
      drip = this.generateDrip();
      this.drips.push(drip);
      return this.scene.add(drip);
    };

    return Dripper;

  })(Backbone.Model);

}).call(this);
