// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.Dripper = (function(_super) {
    __extends(Dripper, _super);

    function Dripper(_opts) {
      this.options = _opts || {};
      this.init();
    }

    Dripper.prototype.init = function() {
      var geometry, material;
      this.destroy();
      this.scene = this.options.scene;
      this.camera = this.options.camera;
      geometry = new THREE.CubeGeometry(1, 1, 1);
      material = new THREE.MeshBasicMaterial({
        color: 0x00ff00
      });
      this.cube = new THREE.Mesh(geometry, material);
      this.scene.add(this.cube);
      return this.camera.position.z = 5;
    };

    Dripper.prototype.destroy = function() {
      this.trigger('destroy');
      if (this.cube) {
        this.scene.remove(this.cube);
        this.cube = void 0;
      }
      return this.scene = this.camera = void 0;
    };

    Dripper.prototype.update = function() {
      return this.cube.position.set(Math.random(1), 0, 0);
    };

    return Dripper;

  })(Backbone.Model);

}).call(this);
