// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.PostProcessor = (function(_super) {
    __extends(PostProcessor, _super);

    function PostProcessor(_opts) {
      this.options = _opts || {};
      this.init();
    }

    PostProcessor.prototype.init = function() {
      this.destroy();
      this.renderer = this.options.renderer;
      this.scene = this.options.scene;
      this.camera = this.options.camera;
      this.composer = new THREE.EffectComposer(this.renderer);
      this.composer.addPass(new THREE.RenderPass(this.scene, this.camera));
      this.effect1 = new THREE.ShaderPass(THREE.DotScreenShader);
      this.effect1.uniforms['scale'].value = 4;
      this.composer.addPass(this.effect1);
      this.effect2 = new THREE.ShaderPass(THREE.RGBShiftShader);
      this.effect2.uniforms['amount'].value = 0.0015;
      this.effect2.renderToScreen = true;
      return this.composer.addPass(this.effect2);
    };

    PostProcessor.prototype.destroy = function() {
      this.trigger('destroy');
      if (this.composer) {
        this.composer = void 0;
      }
      return this.scene = this.camera = void 0;
    };

    PostProcessor.prototype.update = function() {
      this.frame || (this.frame = 0);
      this.effect2.uniforms.amplitude.value = Math.sin(this.frame) * 0.1;
      return this.frame += 0.05;
    };

    return PostProcessor;

  })(Backbone.Model);

}).call(this);
