// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.PostProcessor = (function(_super) {
    __extends(PostProcessor, _super);

    function PostProcessor(_opts) {
      this.options = _opts || {};
      this.init();
    }

    PostProcessor.prototype.init = function() {
      var effect;
      this.destroy();
      this.renderer = this.options.renderer;
      this.scene = this.options.scene;
      this.camera = this.options.camera;
      this.composer = new THREE.EffectComposer(this.renderer);
      this.composer.addPass(new THREE.RenderPass(this.scene, this.camera));
      effect = new THREE.ShaderPass(THREE.DotScreenShader);
      effect.uniforms['scale'].value = 4;
      this.composer.addPass(effect);
      effect = new THREE.ShaderPass(THREE.RGBShiftShader);
      effect.uniforms['amount'].value = 0.0015;
      effect.renderToScreen = true;
      return this.composer.addPass(effect);
    };

    PostProcessor.prototype.destroy = function() {
      this.trigger('destroy');
      if (this.composer) {
        this.composer = void 0;
      }
      return this.scene = this.camera = void 0;
    };

    return PostProcessor;

  })(Backbone.Model);

}).call(this);
